services:
  instagram-cancellation:
    build: .
    container_name: instagram-cancellation
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true